### ISSUE TITLE
Documentation Roadmap

### ISSUE THREAD

**Issue by Bluenix2** [Bluenix2/wumpy#1]
## Description

This issue will be used as the roadmap keeping track of the documentation and scoping out pages as well as coordination.

## Tasks

- [x] Creating slash commands
- [x] Simple options
- [x] Optional options
- [x] Subcommands
  - [x] Subcommand groups
  - [x] Double-nested subcommands
- [x] Context menus
  - [x] Message commands
  - [x] User commands
  - [ ] Member commands
- [x] Option choices
- [ ] Multiple options
- [ ] Advanced option types
  - [ ] Users and roles
  - [ ] Channel types
- [ ] Slash commands permission management
- [ ] Guild-specific commands
